// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserInformations.proto

package TemporaryStorageInJvm;

public final class UserInformations {
  private UserInformations() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TemporaryStorageInJvm.UserDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 Rc = 1;</code>
     * @return Whether the rc field is set.
     */
    boolean hasRc();
    /**
     * <code>optional int32 Rc = 1;</code>
     * @return The rc.
     */
    int getRc();

    /**
     * <code>optional int32 Zid = 2;</code>
     * @return Whether the zid field is set.
     */
    boolean hasZid();
    /**
     * <code>optional int32 Zid = 2;</code>
     * @return The zid.
     */
    int getZid();

    /**
     * <code>optional int32 Depost = 3;</code>
     * @return Whether the depost field is set.
     */
    boolean hasDepost();
    /**
     * <code>optional int32 Depost = 3;</code>
     * @return The depost.
     */
    int getDepost();

    /**
     * <code>optional int32 Withdraw = 4;</code>
     * @return Whether the withdraw field is set.
     */
    boolean hasWithdraw();
    /**
     * <code>optional int32 Withdraw = 4;</code>
     * @return The withdraw.
     */
    int getWithdraw();

    /**
     * <code>optional int32 SendZid = 5;</code>
     * @return Whether the sendZid field is set.
     */
    boolean hasSendZid();
    /**
     * <code>optional int32 SendZid = 5;</code>
     * @return The sendZid.
     */
    int getSendZid();

    /**
     * <code>optional int32 ZidAmount = 6;</code>
     * @return Whether the zidAmount field is set.
     */
    boolean hasZidAmount();
    /**
     * <code>optional int32 ZidAmount = 6;</code>
     * @return The zidAmount.
     */
    int getZidAmount();

    /**
     * <code>optional int32 Type = 7;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>optional int32 Type = 7;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>optional int32 AgentUserZid = 8;</code>
     * @return Whether the agentUserZid field is set.
     */
    boolean hasAgentUserZid();
    /**
     * <code>optional int32 AgentUserZid = 8;</code>
     * @return The agentUserZid.
     */
    int getAgentUserZid();

    /**
     * <code>optional bool Access = 9;</code>
     * @return Whether the access field is set.
     */
    boolean hasAccess();
    /**
     * <code>optional bool Access = 9;</code>
     * @return The access.
     */
    boolean getAccess();

    /**
     * <code>optional int64 Phone = 10;</code>
     * @return Whether the phone field is set.
     */
    boolean hasPhone();
    /**
     * <code>optional int64 Phone = 10;</code>
     * @return The phone.
     */
    long getPhone();

    /**
     * <code>optional string Name = 11;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string Name = 11;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>optional string Name = 11;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string Email = 12;</code>
     * @return Whether the email field is set.
     */
    boolean hasEmail();
    /**
     * <code>optional string Email = 12;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>optional string Email = 12;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>optional string Hid = 13;</code>
     * @return Whether the hid field is set.
     */
    boolean hasHid();
    /**
     * <code>optional string Hid = 13;</code>
     * @return The hid.
     */
    java.lang.String getHid();
    /**
     * <code>optional string Hid = 13;</code>
     * @return The bytes for hid.
     */
    com.google.protobuf.ByteString
        getHidBytes();

    /**
     * <code>optional string Password = 14;</code>
     * @return Whether the password field is set.
     */
    boolean hasPassword();
    /**
     * <code>optional string Password = 14;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>optional string Password = 14;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional string AgentUserNewPassword = 15;</code>
     * @return Whether the agentUserNewPassword field is set.
     */
    boolean hasAgentUserNewPassword();
    /**
     * <code>optional string AgentUserNewPassword = 15;</code>
     * @return The agentUserNewPassword.
     */
    java.lang.String getAgentUserNewPassword();
    /**
     * <code>optional string AgentUserNewPassword = 15;</code>
     * @return The bytes for agentUserNewPassword.
     */
    com.google.protobuf.ByteString
        getAgentUserNewPasswordBytes();

    /**
     * <code>optional string ResetPassword = 16;</code>
     * @return Whether the resetPassword field is set.
     */
    boolean hasResetPassword();
    /**
     * <code>optional string ResetPassword = 16;</code>
     * @return The resetPassword.
     */
    java.lang.String getResetPassword();
    /**
     * <code>optional string ResetPassword = 16;</code>
     * @return The bytes for resetPassword.
     */
    com.google.protobuf.ByteString
        getResetPasswordBytes();

    /**
     * <code>optional string Message = 17;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>optional string Message = 17;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>optional string Message = 17;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>optional string AccessGivenTo = 18;</code>
     * @return Whether the accessGivenTo field is set.
     */
    boolean hasAccessGivenTo();
    /**
     * <code>optional string AccessGivenTo = 18;</code>
     * @return The accessGivenTo.
     */
    java.lang.String getAccessGivenTo();
    /**
     * <code>optional string AccessGivenTo = 18;</code>
     * @return The bytes for accessGivenTo.
     */
    com.google.protobuf.ByteString
        getAccessGivenToBytes();
  }
  /**
   * Protobuf type {@code TemporaryStorageInJvm.UserDetails}
   */
  public static final class UserDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TemporaryStorageInJvm.UserDetails)
      UserDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserDetails.newBuilder() to construct.
    private UserDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserDetails() {
      name_ = "";
      email_ = "";
      hid_ = "";
      password_ = "";
      agentUserNewPassword_ = "";
      resetPassword_ = "";
      message_ = "";
      accessGivenTo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              rc_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              zid_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              depost_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              withdraw_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              sendZid_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              zidAmount_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              type_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              agentUserZid_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              access_ = input.readBool();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              phone_ = input.readInt64();
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              name_ = bs;
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000800;
              email_ = bs;
              break;
            }
            case 106: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00001000;
              hid_ = bs;
              break;
            }
            case 114: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00002000;
              password_ = bs;
              break;
            }
            case 122: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00004000;
              agentUserNewPassword_ = bs;
              break;
            }
            case 130: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00008000;
              resetPassword_ = bs;
              break;
            }
            case 138: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00010000;
              message_ = bs;
              break;
            }
            case 146: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00020000;
              accessGivenTo_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TemporaryStorageInJvm.UserInformations.internal_static_TemporaryStorageInJvm_UserDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TemporaryStorageInJvm.UserInformations.internal_static_TemporaryStorageInJvm_UserDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TemporaryStorageInJvm.UserInformations.UserDetails.class, TemporaryStorageInJvm.UserInformations.UserDetails.Builder.class);
    }

    private int bitField0_;
    public static final int RC_FIELD_NUMBER = 1;
    private int rc_;
    /**
     * <code>optional int32 Rc = 1;</code>
     * @return Whether the rc field is set.
     */
    @java.lang.Override
    public boolean hasRc() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 Rc = 1;</code>
     * @return The rc.
     */
    @java.lang.Override
    public int getRc() {
      return rc_;
    }

    public static final int ZID_FIELD_NUMBER = 2;
    private int zid_;
    /**
     * <code>optional int32 Zid = 2;</code>
     * @return Whether the zid field is set.
     */
    @java.lang.Override
    public boolean hasZid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 Zid = 2;</code>
     * @return The zid.
     */
    @java.lang.Override
    public int getZid() {
      return zid_;
    }

    public static final int DEPOST_FIELD_NUMBER = 3;
    private int depost_;
    /**
     * <code>optional int32 Depost = 3;</code>
     * @return Whether the depost field is set.
     */
    @java.lang.Override
    public boolean hasDepost() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 Depost = 3;</code>
     * @return The depost.
     */
    @java.lang.Override
    public int getDepost() {
      return depost_;
    }

    public static final int WITHDRAW_FIELD_NUMBER = 4;
    private int withdraw_;
    /**
     * <code>optional int32 Withdraw = 4;</code>
     * @return Whether the withdraw field is set.
     */
    @java.lang.Override
    public boolean hasWithdraw() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 Withdraw = 4;</code>
     * @return The withdraw.
     */
    @java.lang.Override
    public int getWithdraw() {
      return withdraw_;
    }

    public static final int SENDZID_FIELD_NUMBER = 5;
    private int sendZid_;
    /**
     * <code>optional int32 SendZid = 5;</code>
     * @return Whether the sendZid field is set.
     */
    @java.lang.Override
    public boolean hasSendZid() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 SendZid = 5;</code>
     * @return The sendZid.
     */
    @java.lang.Override
    public int getSendZid() {
      return sendZid_;
    }

    public static final int ZIDAMOUNT_FIELD_NUMBER = 6;
    private int zidAmount_;
    /**
     * <code>optional int32 ZidAmount = 6;</code>
     * @return Whether the zidAmount field is set.
     */
    @java.lang.Override
    public boolean hasZidAmount() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int32 ZidAmount = 6;</code>
     * @return The zidAmount.
     */
    @java.lang.Override
    public int getZidAmount() {
      return zidAmount_;
    }

    public static final int TYPE_FIELD_NUMBER = 7;
    private int type_;
    /**
     * <code>optional int32 Type = 7;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int32 Type = 7;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int AGENTUSERZID_FIELD_NUMBER = 8;
    private int agentUserZid_;
    /**
     * <code>optional int32 AgentUserZid = 8;</code>
     * @return Whether the agentUserZid field is set.
     */
    @java.lang.Override
    public boolean hasAgentUserZid() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional int32 AgentUserZid = 8;</code>
     * @return The agentUserZid.
     */
    @java.lang.Override
    public int getAgentUserZid() {
      return agentUserZid_;
    }

    public static final int ACCESS_FIELD_NUMBER = 9;
    private boolean access_;
    /**
     * <code>optional bool Access = 9;</code>
     * @return Whether the access field is set.
     */
    @java.lang.Override
    public boolean hasAccess() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional bool Access = 9;</code>
     * @return The access.
     */
    @java.lang.Override
    public boolean getAccess() {
      return access_;
    }

    public static final int PHONE_FIELD_NUMBER = 10;
    private long phone_;
    /**
     * <code>optional int64 Phone = 10;</code>
     * @return Whether the phone field is set.
     */
    @java.lang.Override
    public boolean hasPhone() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional int64 Phone = 10;</code>
     * @return The phone.
     */
    @java.lang.Override
    public long getPhone() {
      return phone_;
    }

    public static final int NAME_FIELD_NUMBER = 11;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string Name = 11;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional string Name = 11;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Name = 11;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 12;
    private volatile java.lang.Object email_;
    /**
     * <code>optional string Email = 12;</code>
     * @return Whether the email field is set.
     */
    @java.lang.Override
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>optional string Email = 12;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Email = 12;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HID_FIELD_NUMBER = 13;
    private volatile java.lang.Object hid_;
    /**
     * <code>optional string Hid = 13;</code>
     * @return Whether the hid field is set.
     */
    @java.lang.Override
    public boolean hasHid() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <code>optional string Hid = 13;</code>
     * @return The hid.
     */
    @java.lang.Override
    public java.lang.String getHid() {
      java.lang.Object ref = hid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Hid = 13;</code>
     * @return The bytes for hid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHidBytes() {
      java.lang.Object ref = hid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 14;
    private volatile java.lang.Object password_;
    /**
     * <code>optional string Password = 14;</code>
     * @return Whether the password field is set.
     */
    @java.lang.Override
    public boolean hasPassword() {
      return ((bitField0_ & 0x00002000) != 0);
    }
    /**
     * <code>optional string Password = 14;</code>
     * @return The password.
     */
    @java.lang.Override
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Password = 14;</code>
     * @return The bytes for password.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGENTUSERNEWPASSWORD_FIELD_NUMBER = 15;
    private volatile java.lang.Object agentUserNewPassword_;
    /**
     * <code>optional string AgentUserNewPassword = 15;</code>
     * @return Whether the agentUserNewPassword field is set.
     */
    @java.lang.Override
    public boolean hasAgentUserNewPassword() {
      return ((bitField0_ & 0x00004000) != 0);
    }
    /**
     * <code>optional string AgentUserNewPassword = 15;</code>
     * @return The agentUserNewPassword.
     */
    @java.lang.Override
    public java.lang.String getAgentUserNewPassword() {
      java.lang.Object ref = agentUserNewPassword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          agentUserNewPassword_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string AgentUserNewPassword = 15;</code>
     * @return The bytes for agentUserNewPassword.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAgentUserNewPasswordBytes() {
      java.lang.Object ref = agentUserNewPassword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        agentUserNewPassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESETPASSWORD_FIELD_NUMBER = 16;
    private volatile java.lang.Object resetPassword_;
    /**
     * <code>optional string ResetPassword = 16;</code>
     * @return Whether the resetPassword field is set.
     */
    @java.lang.Override
    public boolean hasResetPassword() {
      return ((bitField0_ & 0x00008000) != 0);
    }
    /**
     * <code>optional string ResetPassword = 16;</code>
     * @return The resetPassword.
     */
    @java.lang.Override
    public java.lang.String getResetPassword() {
      java.lang.Object ref = resetPassword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resetPassword_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ResetPassword = 16;</code>
     * @return The bytes for resetPassword.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResetPasswordBytes() {
      java.lang.Object ref = resetPassword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resetPassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 17;
    private volatile java.lang.Object message_;
    /**
     * <code>optional string Message = 17;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return ((bitField0_ & 0x00010000) != 0);
    }
    /**
     * <code>optional string Message = 17;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Message = 17;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCESSGIVENTO_FIELD_NUMBER = 18;
    private volatile java.lang.Object accessGivenTo_;
    /**
     * <code>optional string AccessGivenTo = 18;</code>
     * @return Whether the accessGivenTo field is set.
     */
    @java.lang.Override
    public boolean hasAccessGivenTo() {
      return ((bitField0_ & 0x00020000) != 0);
    }
    /**
     * <code>optional string AccessGivenTo = 18;</code>
     * @return The accessGivenTo.
     */
    @java.lang.Override
    public java.lang.String getAccessGivenTo() {
      java.lang.Object ref = accessGivenTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accessGivenTo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string AccessGivenTo = 18;</code>
     * @return The bytes for accessGivenTo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccessGivenToBytes() {
      java.lang.Object ref = accessGivenTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessGivenTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, rc_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, zid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, depost_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, withdraw_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, sendZid_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, zidAmount_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt32(7, type_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeInt32(8, agentUserZid_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeBool(9, access_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        output.writeInt64(10, phone_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, name_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, email_);
      }
      if (((bitField0_ & 0x00001000) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, hid_);
      }
      if (((bitField0_ & 0x00002000) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, password_);
      }
      if (((bitField0_ & 0x00004000) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, agentUserNewPassword_);
      }
      if (((bitField0_ & 0x00008000) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, resetPassword_);
      }
      if (((bitField0_ & 0x00010000) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 17, message_);
      }
      if (((bitField0_ & 0x00020000) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 18, accessGivenTo_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rc_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, zid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, depost_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, withdraw_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, sendZid_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, zidAmount_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, type_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, agentUserZid_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, access_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, phone_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, name_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, email_);
      }
      if (((bitField0_ & 0x00001000) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, hid_);
      }
      if (((bitField0_ & 0x00002000) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, password_);
      }
      if (((bitField0_ & 0x00004000) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, agentUserNewPassword_);
      }
      if (((bitField0_ & 0x00008000) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, resetPassword_);
      }
      if (((bitField0_ & 0x00010000) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, message_);
      }
      if (((bitField0_ & 0x00020000) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, accessGivenTo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TemporaryStorageInJvm.UserInformations.UserDetails)) {
        return super.equals(obj);
      }
      TemporaryStorageInJvm.UserInformations.UserDetails other = (TemporaryStorageInJvm.UserInformations.UserDetails) obj;

      if (hasRc() != other.hasRc()) return false;
      if (hasRc()) {
        if (getRc()
            != other.getRc()) return false;
      }
      if (hasZid() != other.hasZid()) return false;
      if (hasZid()) {
        if (getZid()
            != other.getZid()) return false;
      }
      if (hasDepost() != other.hasDepost()) return false;
      if (hasDepost()) {
        if (getDepost()
            != other.getDepost()) return false;
      }
      if (hasWithdraw() != other.hasWithdraw()) return false;
      if (hasWithdraw()) {
        if (getWithdraw()
            != other.getWithdraw()) return false;
      }
      if (hasSendZid() != other.hasSendZid()) return false;
      if (hasSendZid()) {
        if (getSendZid()
            != other.getSendZid()) return false;
      }
      if (hasZidAmount() != other.hasZidAmount()) return false;
      if (hasZidAmount()) {
        if (getZidAmount()
            != other.getZidAmount()) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (getType()
            != other.getType()) return false;
      }
      if (hasAgentUserZid() != other.hasAgentUserZid()) return false;
      if (hasAgentUserZid()) {
        if (getAgentUserZid()
            != other.getAgentUserZid()) return false;
      }
      if (hasAccess() != other.hasAccess()) return false;
      if (hasAccess()) {
        if (getAccess()
            != other.getAccess()) return false;
      }
      if (hasPhone() != other.hasPhone()) return false;
      if (hasPhone()) {
        if (getPhone()
            != other.getPhone()) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasEmail() != other.hasEmail()) return false;
      if (hasEmail()) {
        if (!getEmail()
            .equals(other.getEmail())) return false;
      }
      if (hasHid() != other.hasHid()) return false;
      if (hasHid()) {
        if (!getHid()
            .equals(other.getHid())) return false;
      }
      if (hasPassword() != other.hasPassword()) return false;
      if (hasPassword()) {
        if (!getPassword()
            .equals(other.getPassword())) return false;
      }
      if (hasAgentUserNewPassword() != other.hasAgentUserNewPassword()) return false;
      if (hasAgentUserNewPassword()) {
        if (!getAgentUserNewPassword()
            .equals(other.getAgentUserNewPassword())) return false;
      }
      if (hasResetPassword() != other.hasResetPassword()) return false;
      if (hasResetPassword()) {
        if (!getResetPassword()
            .equals(other.getResetPassword())) return false;
      }
      if (hasMessage() != other.hasMessage()) return false;
      if (hasMessage()) {
        if (!getMessage()
            .equals(other.getMessage())) return false;
      }
      if (hasAccessGivenTo() != other.hasAccessGivenTo()) return false;
      if (hasAccessGivenTo()) {
        if (!getAccessGivenTo()
            .equals(other.getAccessGivenTo())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRc()) {
        hash = (37 * hash) + RC_FIELD_NUMBER;
        hash = (53 * hash) + getRc();
      }
      if (hasZid()) {
        hash = (37 * hash) + ZID_FIELD_NUMBER;
        hash = (53 * hash) + getZid();
      }
      if (hasDepost()) {
        hash = (37 * hash) + DEPOST_FIELD_NUMBER;
        hash = (53 * hash) + getDepost();
      }
      if (hasWithdraw()) {
        hash = (37 * hash) + WITHDRAW_FIELD_NUMBER;
        hash = (53 * hash) + getWithdraw();
      }
      if (hasSendZid()) {
        hash = (37 * hash) + SENDZID_FIELD_NUMBER;
        hash = (53 * hash) + getSendZid();
      }
      if (hasZidAmount()) {
        hash = (37 * hash) + ZIDAMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getZidAmount();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      if (hasAgentUserZid()) {
        hash = (37 * hash) + AGENTUSERZID_FIELD_NUMBER;
        hash = (53 * hash) + getAgentUserZid();
      }
      if (hasAccess()) {
        hash = (37 * hash) + ACCESS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getAccess());
      }
      if (hasPhone()) {
        hash = (37 * hash) + PHONE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getPhone());
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasEmail()) {
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmail().hashCode();
      }
      if (hasHid()) {
        hash = (37 * hash) + HID_FIELD_NUMBER;
        hash = (53 * hash) + getHid().hashCode();
      }
      if (hasPassword()) {
        hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getPassword().hashCode();
      }
      if (hasAgentUserNewPassword()) {
        hash = (37 * hash) + AGENTUSERNEWPASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getAgentUserNewPassword().hashCode();
      }
      if (hasResetPassword()) {
        hash = (37 * hash) + RESETPASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getResetPassword().hashCode();
      }
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      if (hasAccessGivenTo()) {
        hash = (37 * hash) + ACCESSGIVENTO_FIELD_NUMBER;
        hash = (53 * hash) + getAccessGivenTo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TemporaryStorageInJvm.UserInformations.UserDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TemporaryStorageInJvm.UserInformations.UserDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TemporaryStorageInJvm.UserInformations.UserDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TemporaryStorageInJvm.UserInformations.UserDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TemporaryStorageInJvm.UserInformations.UserDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TemporaryStorageInJvm.UserInformations.UserDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TemporaryStorageInJvm.UserInformations.UserDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TemporaryStorageInJvm.UserInformations.UserDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TemporaryStorageInJvm.UserInformations.UserDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TemporaryStorageInJvm.UserInformations.UserDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TemporaryStorageInJvm.UserInformations.UserDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TemporaryStorageInJvm.UserInformations.UserDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TemporaryStorageInJvm.UserInformations.UserDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TemporaryStorageInJvm.UserDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TemporaryStorageInJvm.UserDetails)
        TemporaryStorageInJvm.UserInformations.UserDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TemporaryStorageInJvm.UserInformations.internal_static_TemporaryStorageInJvm_UserDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TemporaryStorageInJvm.UserInformations.internal_static_TemporaryStorageInJvm_UserDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TemporaryStorageInJvm.UserInformations.UserDetails.class, TemporaryStorageInJvm.UserInformations.UserDetails.Builder.class);
      }

      // Construct using TemporaryStorageInJvm.UserInformations.UserDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rc_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        zid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        depost_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        withdraw_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        sendZid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        zidAmount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        agentUserZid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        access_ = false;
        bitField0_ = (bitField0_ & ~0x00000100);
        phone_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        hid_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        agentUserNewPassword_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        resetPassword_ = "";
        bitField0_ = (bitField0_ & ~0x00008000);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00010000);
        accessGivenTo_ = "";
        bitField0_ = (bitField0_ & ~0x00020000);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TemporaryStorageInJvm.UserInformations.internal_static_TemporaryStorageInJvm_UserDetails_descriptor;
      }

      @java.lang.Override
      public TemporaryStorageInJvm.UserInformations.UserDetails getDefaultInstanceForType() {
        return TemporaryStorageInJvm.UserInformations.UserDetails.getDefaultInstance();
      }

      @java.lang.Override
      public TemporaryStorageInJvm.UserInformations.UserDetails build() {
        TemporaryStorageInJvm.UserInformations.UserDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TemporaryStorageInJvm.UserInformations.UserDetails buildPartial() {
        TemporaryStorageInJvm.UserInformations.UserDetails result = new TemporaryStorageInJvm.UserInformations.UserDetails(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.rc_ = rc_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.zid_ = zid_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.depost_ = depost_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.withdraw_ = withdraw_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.sendZid_ = sendZid_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.zidAmount_ = zidAmount_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.agentUserZid_ = agentUserZid_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.access_ = access_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.phone_ = phone_;
          to_bitField0_ |= 0x00000200;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          to_bitField0_ |= 0x00000400;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000800) != 0)) {
          to_bitField0_ |= 0x00000800;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00001000) != 0)) {
          to_bitField0_ |= 0x00001000;
        }
        result.hid_ = hid_;
        if (((from_bitField0_ & 0x00002000) != 0)) {
          to_bitField0_ |= 0x00002000;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00004000) != 0)) {
          to_bitField0_ |= 0x00004000;
        }
        result.agentUserNewPassword_ = agentUserNewPassword_;
        if (((from_bitField0_ & 0x00008000) != 0)) {
          to_bitField0_ |= 0x00008000;
        }
        result.resetPassword_ = resetPassword_;
        if (((from_bitField0_ & 0x00010000) != 0)) {
          to_bitField0_ |= 0x00010000;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00020000) != 0)) {
          to_bitField0_ |= 0x00020000;
        }
        result.accessGivenTo_ = accessGivenTo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TemporaryStorageInJvm.UserInformations.UserDetails) {
          return mergeFrom((TemporaryStorageInJvm.UserInformations.UserDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TemporaryStorageInJvm.UserInformations.UserDetails other) {
        if (other == TemporaryStorageInJvm.UserInformations.UserDetails.getDefaultInstance()) return this;
        if (other.hasRc()) {
          setRc(other.getRc());
        }
        if (other.hasZid()) {
          setZid(other.getZid());
        }
        if (other.hasDepost()) {
          setDepost(other.getDepost());
        }
        if (other.hasWithdraw()) {
          setWithdraw(other.getWithdraw());
        }
        if (other.hasSendZid()) {
          setSendZid(other.getSendZid());
        }
        if (other.hasZidAmount()) {
          setZidAmount(other.getZidAmount());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasAgentUserZid()) {
          setAgentUserZid(other.getAgentUserZid());
        }
        if (other.hasAccess()) {
          setAccess(other.getAccess());
        }
        if (other.hasPhone()) {
          setPhone(other.getPhone());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000400;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000800;
          email_ = other.email_;
          onChanged();
        }
        if (other.hasHid()) {
          bitField0_ |= 0x00001000;
          hid_ = other.hid_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00002000;
          password_ = other.password_;
          onChanged();
        }
        if (other.hasAgentUserNewPassword()) {
          bitField0_ |= 0x00004000;
          agentUserNewPassword_ = other.agentUserNewPassword_;
          onChanged();
        }
        if (other.hasResetPassword()) {
          bitField0_ |= 0x00008000;
          resetPassword_ = other.resetPassword_;
          onChanged();
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00010000;
          message_ = other.message_;
          onChanged();
        }
        if (other.hasAccessGivenTo()) {
          bitField0_ |= 0x00020000;
          accessGivenTo_ = other.accessGivenTo_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TemporaryStorageInJvm.UserInformations.UserDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TemporaryStorageInJvm.UserInformations.UserDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int rc_ ;
      /**
       * <code>optional int32 Rc = 1;</code>
       * @return Whether the rc field is set.
       */
      @java.lang.Override
      public boolean hasRc() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 Rc = 1;</code>
       * @return The rc.
       */
      @java.lang.Override
      public int getRc() {
        return rc_;
      }
      /**
       * <code>optional int32 Rc = 1;</code>
       * @param value The rc to set.
       * @return This builder for chaining.
       */
      public Builder setRc(int value) {
        bitField0_ |= 0x00000001;
        rc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 Rc = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRc() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rc_ = 0;
        onChanged();
        return this;
      }

      private int zid_ ;
      /**
       * <code>optional int32 Zid = 2;</code>
       * @return Whether the zid field is set.
       */
      @java.lang.Override
      public boolean hasZid() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 Zid = 2;</code>
       * @return The zid.
       */
      @java.lang.Override
      public int getZid() {
        return zid_;
      }
      /**
       * <code>optional int32 Zid = 2;</code>
       * @param value The zid to set.
       * @return This builder for chaining.
       */
      public Builder setZid(int value) {
        bitField0_ |= 0x00000002;
        zid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 Zid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearZid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        zid_ = 0;
        onChanged();
        return this;
      }

      private int depost_ ;
      /**
       * <code>optional int32 Depost = 3;</code>
       * @return Whether the depost field is set.
       */
      @java.lang.Override
      public boolean hasDepost() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 Depost = 3;</code>
       * @return The depost.
       */
      @java.lang.Override
      public int getDepost() {
        return depost_;
      }
      /**
       * <code>optional int32 Depost = 3;</code>
       * @param value The depost to set.
       * @return This builder for chaining.
       */
      public Builder setDepost(int value) {
        bitField0_ |= 0x00000004;
        depost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 Depost = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDepost() {
        bitField0_ = (bitField0_ & ~0x00000004);
        depost_ = 0;
        onChanged();
        return this;
      }

      private int withdraw_ ;
      /**
       * <code>optional int32 Withdraw = 4;</code>
       * @return Whether the withdraw field is set.
       */
      @java.lang.Override
      public boolean hasWithdraw() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 Withdraw = 4;</code>
       * @return The withdraw.
       */
      @java.lang.Override
      public int getWithdraw() {
        return withdraw_;
      }
      /**
       * <code>optional int32 Withdraw = 4;</code>
       * @param value The withdraw to set.
       * @return This builder for chaining.
       */
      public Builder setWithdraw(int value) {
        bitField0_ |= 0x00000008;
        withdraw_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 Withdraw = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearWithdraw() {
        bitField0_ = (bitField0_ & ~0x00000008);
        withdraw_ = 0;
        onChanged();
        return this;
      }

      private int sendZid_ ;
      /**
       * <code>optional int32 SendZid = 5;</code>
       * @return Whether the sendZid field is set.
       */
      @java.lang.Override
      public boolean hasSendZid() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 SendZid = 5;</code>
       * @return The sendZid.
       */
      @java.lang.Override
      public int getSendZid() {
        return sendZid_;
      }
      /**
       * <code>optional int32 SendZid = 5;</code>
       * @param value The sendZid to set.
       * @return This builder for chaining.
       */
      public Builder setSendZid(int value) {
        bitField0_ |= 0x00000010;
        sendZid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 SendZid = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendZid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sendZid_ = 0;
        onChanged();
        return this;
      }

      private int zidAmount_ ;
      /**
       * <code>optional int32 ZidAmount = 6;</code>
       * @return Whether the zidAmount field is set.
       */
      @java.lang.Override
      public boolean hasZidAmount() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional int32 ZidAmount = 6;</code>
       * @return The zidAmount.
       */
      @java.lang.Override
      public int getZidAmount() {
        return zidAmount_;
      }
      /**
       * <code>optional int32 ZidAmount = 6;</code>
       * @param value The zidAmount to set.
       * @return This builder for chaining.
       */
      public Builder setZidAmount(int value) {
        bitField0_ |= 0x00000020;
        zidAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ZidAmount = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearZidAmount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        zidAmount_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>optional int32 Type = 7;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override
      public boolean hasType() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional int32 Type = 7;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 Type = 7;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000040;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 Type = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        type_ = 0;
        onChanged();
        return this;
      }

      private int agentUserZid_ ;
      /**
       * <code>optional int32 AgentUserZid = 8;</code>
       * @return Whether the agentUserZid field is set.
       */
      @java.lang.Override
      public boolean hasAgentUserZid() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional int32 AgentUserZid = 8;</code>
       * @return The agentUserZid.
       */
      @java.lang.Override
      public int getAgentUserZid() {
        return agentUserZid_;
      }
      /**
       * <code>optional int32 AgentUserZid = 8;</code>
       * @param value The agentUserZid to set.
       * @return This builder for chaining.
       */
      public Builder setAgentUserZid(int value) {
        bitField0_ |= 0x00000080;
        agentUserZid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 AgentUserZid = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearAgentUserZid() {
        bitField0_ = (bitField0_ & ~0x00000080);
        agentUserZid_ = 0;
        onChanged();
        return this;
      }

      private boolean access_ ;
      /**
       * <code>optional bool Access = 9;</code>
       * @return Whether the access field is set.
       */
      @java.lang.Override
      public boolean hasAccess() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional bool Access = 9;</code>
       * @return The access.
       */
      @java.lang.Override
      public boolean getAccess() {
        return access_;
      }
      /**
       * <code>optional bool Access = 9;</code>
       * @param value The access to set.
       * @return This builder for chaining.
       */
      public Builder setAccess(boolean value) {
        bitField0_ |= 0x00000100;
        access_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool Access = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccess() {
        bitField0_ = (bitField0_ & ~0x00000100);
        access_ = false;
        onChanged();
        return this;
      }

      private long phone_ ;
      /**
       * <code>optional int64 Phone = 10;</code>
       * @return Whether the phone field is set.
       */
      @java.lang.Override
      public boolean hasPhone() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>optional int64 Phone = 10;</code>
       * @return The phone.
       */
      @java.lang.Override
      public long getPhone() {
        return phone_;
      }
      /**
       * <code>optional int64 Phone = 10;</code>
       * @param value The phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhone(long value) {
        bitField0_ |= 0x00000200;
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Phone = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhone() {
        bitField0_ = (bitField0_ & ~0x00000200);
        phone_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string Name = 11;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <code>optional string Name = 11;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Name = 11;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Name = 11;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Name = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000400);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Name = 11;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>optional string Email = 12;</code>
       * @return Whether the email field is set.
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000800) != 0);
      }
      /**
       * <code>optional string Email = 12;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            email_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Email = 12;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Email = 12;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Email = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000800);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Email = 12;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hid_ = "";
      /**
       * <code>optional string Hid = 13;</code>
       * @return Whether the hid field is set.
       */
      public boolean hasHid() {
        return ((bitField0_ & 0x00001000) != 0);
      }
      /**
       * <code>optional string Hid = 13;</code>
       * @return The hid.
       */
      public java.lang.String getHid() {
        java.lang.Object ref = hid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            hid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Hid = 13;</code>
       * @return The bytes for hid.
       */
      public com.google.protobuf.ByteString
          getHidBytes() {
        java.lang.Object ref = hid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Hid = 13;</code>
       * @param value The hid to set.
       * @return This builder for chaining.
       */
      public Builder setHid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        hid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Hid = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearHid() {
        bitField0_ = (bitField0_ & ~0x00001000);
        hid_ = getDefaultInstance().getHid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Hid = 13;</code>
       * @param value The bytes for hid to set.
       * @return This builder for chaining.
       */
      public Builder setHidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        hid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>optional string Password = 14;</code>
       * @return Whether the password field is set.
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00002000) != 0);
      }
      /**
       * <code>optional string Password = 14;</code>
       * @return The password.
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Password = 14;</code>
       * @return The bytes for password.
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Password = 14;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Password = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00002000);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Password = 14;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        password_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object agentUserNewPassword_ = "";
      /**
       * <code>optional string AgentUserNewPassword = 15;</code>
       * @return Whether the agentUserNewPassword field is set.
       */
      public boolean hasAgentUserNewPassword() {
        return ((bitField0_ & 0x00004000) != 0);
      }
      /**
       * <code>optional string AgentUserNewPassword = 15;</code>
       * @return The agentUserNewPassword.
       */
      public java.lang.String getAgentUserNewPassword() {
        java.lang.Object ref = agentUserNewPassword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            agentUserNewPassword_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string AgentUserNewPassword = 15;</code>
       * @return The bytes for agentUserNewPassword.
       */
      public com.google.protobuf.ByteString
          getAgentUserNewPasswordBytes() {
        java.lang.Object ref = agentUserNewPassword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          agentUserNewPassword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string AgentUserNewPassword = 15;</code>
       * @param value The agentUserNewPassword to set.
       * @return This builder for chaining.
       */
      public Builder setAgentUserNewPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        agentUserNewPassword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string AgentUserNewPassword = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearAgentUserNewPassword() {
        bitField0_ = (bitField0_ & ~0x00004000);
        agentUserNewPassword_ = getDefaultInstance().getAgentUserNewPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string AgentUserNewPassword = 15;</code>
       * @param value The bytes for agentUserNewPassword to set.
       * @return This builder for chaining.
       */
      public Builder setAgentUserNewPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        agentUserNewPassword_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object resetPassword_ = "";
      /**
       * <code>optional string ResetPassword = 16;</code>
       * @return Whether the resetPassword field is set.
       */
      public boolean hasResetPassword() {
        return ((bitField0_ & 0x00008000) != 0);
      }
      /**
       * <code>optional string ResetPassword = 16;</code>
       * @return The resetPassword.
       */
      public java.lang.String getResetPassword() {
        java.lang.Object ref = resetPassword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            resetPassword_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ResetPassword = 16;</code>
       * @return The bytes for resetPassword.
       */
      public com.google.protobuf.ByteString
          getResetPasswordBytes() {
        java.lang.Object ref = resetPassword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resetPassword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ResetPassword = 16;</code>
       * @param value The resetPassword to set.
       * @return This builder for chaining.
       */
      public Builder setResetPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        resetPassword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResetPassword = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearResetPassword() {
        bitField0_ = (bitField0_ & ~0x00008000);
        resetPassword_ = getDefaultInstance().getResetPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ResetPassword = 16;</code>
       * @param value The bytes for resetPassword to set.
       * @return This builder for chaining.
       */
      public Builder setResetPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        resetPassword_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>optional string Message = 17;</code>
       * @return Whether the message field is set.
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00010000) != 0);
      }
      /**
       * <code>optional string Message = 17;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Message = 17;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Message = 17;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Message = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00010000);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Message = 17;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        message_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object accessGivenTo_ = "";
      /**
       * <code>optional string AccessGivenTo = 18;</code>
       * @return Whether the accessGivenTo field is set.
       */
      public boolean hasAccessGivenTo() {
        return ((bitField0_ & 0x00020000) != 0);
      }
      /**
       * <code>optional string AccessGivenTo = 18;</code>
       * @return The accessGivenTo.
       */
      public java.lang.String getAccessGivenTo() {
        java.lang.Object ref = accessGivenTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            accessGivenTo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string AccessGivenTo = 18;</code>
       * @return The bytes for accessGivenTo.
       */
      public com.google.protobuf.ByteString
          getAccessGivenToBytes() {
        java.lang.Object ref = accessGivenTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accessGivenTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string AccessGivenTo = 18;</code>
       * @param value The accessGivenTo to set.
       * @return This builder for chaining.
       */
      public Builder setAccessGivenTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        accessGivenTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string AccessGivenTo = 18;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccessGivenTo() {
        bitField0_ = (bitField0_ & ~0x00020000);
        accessGivenTo_ = getDefaultInstance().getAccessGivenTo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string AccessGivenTo = 18;</code>
       * @param value The bytes for accessGivenTo to set.
       * @return This builder for chaining.
       */
      public Builder setAccessGivenToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        accessGivenTo_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TemporaryStorageInJvm.UserDetails)
    }

    // @@protoc_insertion_point(class_scope:TemporaryStorageInJvm.UserDetails)
    private static final TemporaryStorageInJvm.UserInformations.UserDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TemporaryStorageInJvm.UserInformations.UserDetails();
    }

    public static TemporaryStorageInJvm.UserInformations.UserDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<UserDetails>
        PARSER = new com.google.protobuf.AbstractParser<UserDetails>() {
      @java.lang.Override
      public UserDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TemporaryStorageInJvm.UserInformations.UserDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TemporaryStorageInJvm_UserDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TemporaryStorageInJvm_UserDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026UserInformations.proto\022\025TemporaryStora" +
      "geInJvm\"\310\002\n\013UserDetails\022\n\n\002Rc\030\001 \001(\005\022\013\n\003Z" +
      "id\030\002 \001(\005\022\016\n\006Depost\030\003 \001(\005\022\020\n\010Withdraw\030\004 \001" +
      "(\005\022\017\n\007SendZid\030\005 \001(\005\022\021\n\tZidAmount\030\006 \001(\005\022\014" +
      "\n\004Type\030\007 \001(\005\022\024\n\014AgentUserZid\030\010 \001(\005\022\016\n\006Ac" +
      "cess\030\t \001(\010\022\r\n\005Phone\030\n \001(\003\022\014\n\004Name\030\013 \001(\t\022" +
      "\r\n\005Email\030\014 \001(\t\022\013\n\003Hid\030\r \001(\t\022\020\n\010Password\030" +
      "\016 \001(\t\022\034\n\024AgentUserNewPassword\030\017 \001(\t\022\025\n\rR" +
      "esetPassword\030\020 \001(\t\022\017\n\007Message\030\021 \001(\t\022\025\n\rA" +
      "ccessGivenTo\030\022 \001(\tB\022B\020UserInformations"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TemporaryStorageInJvm_UserDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TemporaryStorageInJvm_UserDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TemporaryStorageInJvm_UserDetails_descriptor,
        new java.lang.String[] { "Rc", "Zid", "Depost", "Withdraw", "SendZid", "ZidAmount", "Type", "AgentUserZid", "Access", "Phone", "Name", "Email", "Hid", "Password", "AgentUserNewPassword", "ResetPassword", "Message", "AccessGivenTo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
